version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: remoteadmin
      MYSQL_PASSWORD: springcourse
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network   # <-- добавлено сюда

  app:
    build: .
    container_name: spring-app
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: remoteadmin
      SPRING_DATASOURCE_PASSWORD: springcourse
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

networks:
  app-network: